validator-client depends on nymd-client feature
This fixes the following two errors when compiling the mixnode:
error[E0412]: cannot find type `ApiClient` in crate `validator_client`
error[E0433]: failed to resolve: could not find `ApiClient` in `validator_client`